name: Fetch Dollar Rate and Send to Telegram

on:
  schedule:
    - cron: '30 6 * * *' # Runs every day at 10 AM Iran Time (UTC+3:30)
  push:
    branches:
      - main

jobs:
  fetch_and_send:
    runs-on: ubuntu-latest

    steps:
      - name: Get JSON Data from Bonbast
        id: fetch_data
        run: |
          response=$(curl -s 'https://bonbast.info/?ajax=1')
          echo "JSON Response: $response"
          echo "$response" > response.json
          echo "response=$(cat response.json)" >> $GITHUB_ENV

      - name: Extract Dollar Price
        id: extract_price
        run: |
          price1=$(cat response.json | jq -r '.[] | select(.title=="Dollar") | .price1' | tr -d ',')
          echo "Extracted price1: $price1"
          echo "price1=$price1" >> $GITHUB_ENV

      - name: Calculate Division
        id: calculate
        run: |
          secret_number=${{ secrets.NUMBER }}
          result=$(awk "BEGIN {print \$secret_number / ${{ env.price1 }}}")
          echo "Calculated result: $result"
          echo "result=$result" >> $GITHUB_ENV

      - name: Send Message to Telegram
        run: |
          curl -s -o /dev/null -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Result: ${{ env.result }} - ${{ secrets.MESSAGE }}"
